export const tableFields = {
  LIST_USER_ADMIN: [
    {
      key: "action",
      label: "操作",
      _style: "min-width:140px; text-align:center",
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:40px; text-align:center",
      sortable: true,
    },
    {
      key: "account_name",
      label: "ニックネーム",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "email",
      label: "メールアドレス",
      _style: "min-width:200px; text-align:center",
      sortable: true,
    },
    {
      key: "phone_number",
      label: "電話番号(携帯)",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "is_blocked",
      label: "本人確認状態",
      _style: "min-width:150px; text-align:center",
    },
    {
      key: "reason_withdrawal",
      label: "退会理由",
      _style: "min-width:150px; text-align:center",
    },
    {
      key: "status",
      label: "ステータス",
      _style: "min-width:150px; text-align:center",
    },
  ],
  LIST_DELIVERY_MANAGEMENT_SELLER: [
    {
      key: "account_name",
      label: "購入ユーザー",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "buyer_full_name",
      label: "氏名",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "delivery_address",
      label: "配送先住所",
      _style: "min-width:250px; text-align:center",
      sortable: false,
    },
    {
      key: "course_name",
      label: "利用コース",
      _style: "min-width:200px; text-align:center",
      sortable: false,
    },
    {
      key: "estimated_date",
      label: "配送期日",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "actual_date",
      label: "配送日",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "payment_status",
      label: "決済ステータス",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "delivery_status",
      label: "配送ステータス",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
  ],
  LIST_CUSTOMER_MANAGEMENT_SELLER: [
    {
      key: "status",
      label: "ステータス",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "buyer_name",
      label: "購入ユーザー",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "buyer_full_name",
      label: "氏名",
      _style: "min-width:200px; text-align:center",
      sortable: false,
    },
    {
      key: "post_code",
      label: "郵便番号",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "address",
      label: "住所",
      _style: "min-width:250px; text-align:center",
      sortable: false,
    },
    {
      key: "phone_number",
      label: "電話番号(携帯)",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "course_name",
      label: "利用コース",
      _style: "min-width:200px; text-align:center",
      sortable: false,
    },
    {
      key: "contract_date",
      label: "契約日付",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "message",
      label: "メッセージ",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "action",
      label: "状態",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
  ],
  LIST_DELIVERY_MANAGEMENT_BUYER: [
    {
      key: "course_name",
      label: "利用コース名",
      _style: "min-width:250px; text-align:center",
      sortable: false,
    },
    {
      key: "payment_id",
      label: "決済NO.",
      _style: "min-width:100px; text-align:center",
      sortable: false,
    },
    {
      key: "payment_date",
      label: "決済日",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "delivery_address",
      label: "配送先住所",
      _style: "min-width:250px; text-align:center",
      sortable: false,
    },
    {
      key: "payment_status",
      label: "決済ステータス",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "delivery_status",
      label: "配送ステータス",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
  ],
  LIST_DETAIL_PAYMENT: [
    {
      key: "payment_status",
      label: "",
      _style: "min-width:100px; text-align:center",
      sortable: false,
    },
    {
      key: "course_name",
      label: "利用コース名",
      _style: "min-width:200px; text-align:center",
      sortable: false,
    },
    {
      key: "id",
      label: "決済NO.",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "pay_expire_at_date",
      label: "決済日",
      _style: "min-width:100px; text-align:center",
      sortable: false,
    },
    {
      key: "sub_total",
      label: "価格",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "action",
      label: "操作",
      _style: "min-width:100px; text-align:center",
      sortable: false,
    },
  ],
  LIST_SALES_MANAGER: [
    {
      key: "account_name",
      label: "購入ユーザー",
      _style: "min-width:250px; text-align:center",
      sortable: false,
    },
    {
      key: "created_at",
      label: "決済日",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "id",
      label: "決済NO.",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
    {
      key: "course_name",
      label: "利用コース",
      _style: "min-width:250px; text-align:center",
      sortable: false,
    },
    {
      key: "sub_total",
      label: "金額",
      _style: "min-width:100px; text-align:center",
      sortable: false,
    },
    {
      key: "payment_status",
      label: "決済ステータス",
      _style: "min-width:150px; text-align:center",
      sortable: false,
    },
  ],
  LIST_TAG_ADMIN: [
    {
      key: "action",
      label: "操作",
      _style: "min-width:150px; text-align:center",
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:40px; text-align:center",
      sortable: true,
    },
    {
      key: "name",
      label: "タグ名",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "amount_registed",
      label: "登録数量",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "created_at",
      label: "登録日",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "updated_at",
      label: "更新日",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
  ],
  LIST_SERVICE_ADMIN: [
    {
      key: "action",
      label: "",
      _style: "min-width:40px; text-align:center",
      sortable: false,
    },
    {
      key: "id",
      label: "ID",
      _style: "min-width:40px; text-align:center",
      sortable: true,
    },
    {
      key: "seller_id",
      label: "売り手ID",
      _style: "min-width:100px; text-align:center",
      sortable: true,
    },
    {
      key: "seller_name",
      label: "販売者名",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "name",
      label: "サービス名",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "caption",
      label: "キャッチコピー",
      _style: "min-width:250px; text-align:center",
      sortable: true,
    },
    {
      key: "service_content",
      label: "サービス内容の説明",
      _style: "min-width:300px; text-align:center",
      sortable: true,
    },
    {
      key: "enabled",
      label: "承認状況",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "private",
      label: "サービス状態",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
  ],
  LIST_DASHBOARD_SELLER: [
    {
      key: "service_name",
      label: "",
      _style: "min-width:200px; text-align:center",
      sortable: true,
    },
    {
      key: "statistical_access_list_service_page",
      label: "閲覧数 （一覧ページ）",
      _style: "min-width:200px; text-align:center",
    },
    {
      key: "statistical_access_service_detail_page",
      label: "閲覧数 （詳細ページ）",
      _style: "min-width:200px; text-align:center",
    },
    {
      key: "statistical_favorite",
      label: "お気に入り 登録数",
      _style: "min-width:200px; text-align:center",
    },
    {
      key: "statistical_review",
      label: "口コミ数",
      _style: "min-width:200px; text-align:center",
    },
    {
      key: "statistical_rating",
      label: "サービス評価",
      _style: "min-width:200px; text-align:center",
    },
    {
      key: "statistical_contracts",
      label: "契約数",
      _style: "min-width:200px; text-align:center",
    },
    {
      key: "statistical_revenue",
      label: "売上高",
      _style: "min-width:200px; text-align:center",
    },
    {
      key: "statistical_click_official_url",
      label: "公式サイトURL クリック数",
      _style: "min-width:200px; text-align:center",
    },
  ],
  LIST_CONTACT_ADMIN: [
    {
      key: "id",
      label: "ID",
      _style: "min-width:100px; text-align:center",
      sortable: true,
    },
    {
      key: "name",
      label: "お名前",
      _style: "min-width:200px; text-align:center",
      sortable: true,
    },
    {
      key: "email",
      label: "メールアドレス",
      _style: "min-width:250px; text-align:center",
      sortable: true,
    },
    {
      key: "content",
      label: "お問い合わせ内容",
      _style: "min-width:350px; text-align:center",
      sortable: false,
    },
    {
      key: "status",
      label: "ステータス",
      _style: "min-width:200px; text-align:center",
      sortable: false,
    },
    {
      key: "created_at",
      label: "受信日",
      _style: "min-width:200px; text-align:center",
      sortable: true,
    },
    {
      key: "updated_at",
      label: "更新日",
      _style: "min-width:200px; text-align:center",
      sortable: true,
    },
  ],
  LIST_TRANSFER: [
    {
      key: "created_at",
      label: "振込申請日",
      _style: "min-width:200px",
    },
    {
      key: "id",
      label: "申請NO.",
      _style: "min-width:200px",
    },
    {
      key: "transfer_amount",
      label: "振込申請金額",
      _style: "min-width:200px",
    },
    {
      key: "transfer_fee",
      label: "振込手数料",
      _style: "min-width:200px",
    },
    {
      key: "status",
      label: "振込ステータス",
      _style: "min-width:200px",
    },
  ],
  LIST_TRANSFER_ADMIN: [
    {
      key: "id",
      label: "ID",
      _style: "min-width:40px; text-align:center",
      sortable: true,
    },
    {
      key: "account_name",
      label: "アカウント名",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "account_number",
      label: "口座番号",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "account_holder",
      label: "口座名義人",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "financial_institution_name",
      label: "金融機関名",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "transfer_amount",
      label: "払込金額",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "transfer_fee",
      label: "転送料",
      _style: "min-width:200px; text-align:center",
      sortable: true,
    },
    {
      key: "created_at",
      label: "振込申請日",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "status",
      label: "状態",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
  ],
  LIST_REVIEW_ADMIN: [
    {
      key: "id",
      label: "ID",
      _style: "min-width:40px; text-align:center",
      sortable: true,
    },
    {
      key: "buyer_id",
      label: "購入者ID",
      _style: "min-width:100px; text-align:center",
      sortable: true,
    },
    {
      key: "buyer_name",
      label: "買い手の名前",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "name",
      label: "サービス名",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "rating",
      label: "評価",
      _style: "min-width:300px; text-align:center",
      sortable: true,
    },
    {
      key: "description",
      label: "レビュー内容の説明",
      _style: "min-width:300px; text-align:center",
      sortable: true,
    },
    {
      key: "is_active",
      label: "承認状況",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
    {
      key: "seller_reply",
      label: "出品者の返事",
      _style: "min-width:300px; text-align:center",
      sortable: true,
    },
    {
      key: "is_active_seller",
      label: "出品者承認状況",
      _style: "min-width:150px; text-align:center",
      sortable: true,
    },
  ],
  LIST_SHIPPING_INFO: [
    {
      key: "checkbox",
      label: "",
      _style: "min-width:40px; text-align:left",
      sortable: false,
    },
    {
      key: "action",
      label: "",
      _style: "min-width:120px; text-align:left",
      sortable: false,
    },
    {
      key: "name",
      label: "お名前",
      _style: "min-width:150px; text-align:left",
      sortable: false,
    },
    {
      key: "post_code",
      label: "郵便番号",
      _style: "min-width:150px; text-align:left",
      sortable: true,
    },
    {
      key: "address",
      label: "住所",
      _style: "min-width:300px; text-align:left",
      sortable: true,
    },
    {
      key: "phone",
      label: "電話番号",
      _style: "min-width:200px; text-align:left",
      sortable: false,
    },
    {
      key: "name_kana",
      label: "フリガナ",
      _style: "min-width:250px; text-align:left",
      sortable: false,
    },
  ],
};
